#!/usr/bin/env bash

CONFIG_FILE="/custom/caddy/Caddyfile"

declare -A caddy_configs=(
    ["CADDY_WORK_DIR"]="${CADDY_WORK_DIR:-/var/www/}"
    ["CADDY_REAL_IP"]="http.request.header.${CADDY_REAL_IP:-X-Forwarded-For}"
)

for key in "${!caddy_configs[@]}"; do
    sed -i "s|${key}|${caddy_configs[$key]}|g" "$CONFIG_FILE"
done
