#!/usr/bin/env bash

CONFIG_FILE="/custom/php/conf.d/zzz_custom.ini"

declare -A php_configs=(
    ["PHP_MEMORY_LIMIT"]="memory_limit = ${PHP_MEMORY_LIMIT:-64M}"
    ["PHP_POST_MAX_SIZE"]="post_max_size = ${PHP_POST_MAX_SIZE:-1024M}"
    ["PHP_UPLOAD_MAX_FILESIZE"]="upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE:-1024M}"
)

for key in "${!php_configs[@]}"; do
    sed -i "s|${placeholder}|${php_configs[$placeholder]}|g" "$CONFIG_FILE"
done

