#!/usr/bin/env bash

CONFIG_FILE="/custom/php/php-fpm.d/zzz_custom.conf"

declare -A fpm_configs=(
    ["FPM_PM"]="pm = ${FPM_PM:-static}"
    ["FPM_PM_MAX_CHILDREN"]="pm.max_children = ${FPM_PM_MAX_CHILDREN:-5}"
    ["FPM_PM_START_SERVERS"]="pm.start_servers = ${FPM_PM_START_SERVERS:-2}"
    ["FPM_PM_MIN_SPARE_SERVERS"]="pm.min_spare_servers = ${FPM_PM_MIN_SPARE_SERVERS:-1}"
    ["FPM_PM_MAX_SPARE_SERVERS"]="pm.max_spare_servers = ${FPM_PM_MAX_SPARE_SERVERS:-3}"
    ["FPM_PM_MAX_REQUESTS"]="pm.max_requests = ${FPM_PM_MAX_REQUESTS:-500}"
    ["FPM_PHP_ADMIN_VALUE_MEMORY_LIMIT"]="php_admin_value[memory_limit] = ${PHP_MEMORY_LIMIT:-64M}"
)

for key in "${!fpm_configs[@]}"; do
    sed -i "s/^${key}$/${fpm_configs[$key]}/" "$CONFIG_FILE"
done
